version: '3.8'

tasks:
  generate-sso:
    desc: "Generate Go code proto files"
    cmds:
      - mkdir -p gen/go
      - protoc -I proto proto/sso/sso.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative
  clean:
    desc: "Clean generated file"
    cmds:
     - rm -rf gen/go